export const siteConfig = {
  name: "Dinesh Harish Kumar",
  shortName: "Dinesh Kumar",
  title: "Dinesh Harish Kumar | Senior Full Stack Developer & Software Engineer",
  description:
    "Portfolio of Dinesh Harish Kumar, a Full Stack Developer & Software Engineer building high-performance B2B, SaaS, and web applications with React, Next.js, Node.js, and Django.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://dineshkumar9.vercel.app",
  ogImage: "/og-image.png",
  author: {
    name: "Dinesh Harish Kumar",
    email: "dineshkumar.dev@gmail.com",
    url: "https://github.com/jdmkd",
    jobTitle: "Full Stack Developer",
    worksFor: "Freelance / Software Engineer",
    addressLocality: "Ahmedabad",
    addressRegion: "Gujarat",
    addressCountry: "India",
  },
  social: {
    github: "https://github.com/jdmkd",
    linkedin: "https://www.linkedin.com/in/dineshkumarx",
    instagram: "https://www.instagram.com/jd_mkd_09/",
  },
  keywords: [
    "Dinesh Harish Kumar",
    "Dinesh Kumar",
    "Full Stack Developer",
    "Software Engineer",
    "Next.js Developer",
    "React Developer",
    "Node.js Developer",
    "Django REST Framework",
    "Web Performance Engineer",
    "System Architect",
    "Frontend Developer",
    "Backend Engineer",
    "PostgreSQL",
    "MongoDB",
    "Redis Caching",
    "Ahmedabad Software Developer",
    "Vercel Portfolio",
    "Full Stack Web Portfolio",
  ],
};
